routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect()->route('user.register');
});

Route::group(['namespace' => 'User', 'as' => 'user.', 'middleware' => 'guest'], function (){

    Route::get('register', 'RegisterController')->name('register');
    Route::post('register', 'RegisterController@submitForm')->name('register.submit');

    Route::get('login', 'LoginController')->name('login');
    Route::post('login', 'LoginController@submitForm')->name('login.submit');
});

Route::group(['middleware' => 'auth', 'prefix' => 'post', 'as' => 'post.'], function (){
    Route::get('/', 'PostController@index')->name('all');
    Route::post('/', 'PostController@store')->name('submit');
    Route::get('/{id}/edit', 'PostController@edit')->name('edit');
    Route::get('/{id}', 'PostController@show')->name('show');
    Route::put('/{id}', 'PostController@update')->name('update');
});

Route::post('comment/submit/{id}', 'CommentController@submit')->name('post.comment');

app/Category.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Category extends Model
{
    protected $fillable = ['name'];

    public function posts()
    {
        return $this->hasMany(Post::class);
    }
}

app/Comment.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Comment extends Model
{
    protected $fillable = ['comment'];

    public function post()
    {
        return $this->belongsTo(Post::class);
    }

    public function user()
    {
        return $this->belongsTo(User::class);
    }
}

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class User extends Model
{
    //
}

app/Post.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\Storage;

class Post extends Model
{
    const IMAGE_PATH = 'post/image';

    protected $fillable = [ 'name', 'image' ];

    public function category()
    {
        return $this->belongsTo(Category::class);
    }

    public function user()
    {
        return $this->belongsTo(User::class);
    }

    public function getImage()
    {
        return Storage::url($this->image);
    }

    public function comments()
    {
        return $this->hasMany(Comment::class);
    }
}

app/User.php
<?php

namespace App;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'username', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    public function posts()
    {
        return $this->hasMany(Post::class);
    }
}

app/Http/Controllers/CommentController.php
<?php

namespace App\Http\Controllers;

use App\Comment;
use App\Post;
use Illuminate\Http\Request;

class CommentController extends Controller
{
    public function submit($id, Request $request)
    {
       try {

           $post = Post::find($id);

           if(!$post) {
               throw new \Exception('Post not found');
           }

           $user = $request->user();

           $comment = new Comment();
           $comment->comment = $request->comment;
           $comment->user()->associate($user->id);
           $comment->post()->associate($id);
           $comment->save();

           $response = view('post.comment', ['comment' => $comment])->render();

           return ['comment' => $response, 'total' => $post->comments()->count()];

       }catch (\Exception $e)
       {
           return response()->json(['status' => 'fail', 'message' => $e->getMessage()]);
       }
    }
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/PostController.php
<?php

namespace App\Http\Controllers;

use App\Category;
use App\Http\Requests\CreatePost;
use App\Http\Requests\UpdatePost;
use App\Post;
use Illuminate\Http\Request;

class PostController extends Controller
{
    public function index(Request  $request)
    {
        $user = $request->user();
        $categories = Category::pluck('name', 'id');
        $posts = $user->posts()->paginate();
        $post = new Post();

        return view('post.all', ['categories' => $categories, 'posts' => $posts, 'post' => $post]);
    }

    public function store(CreatePost $request)
    {
        $post = new Post();

        $post->name = $request->name;
        $post->category()->associate($request->category);
        $post->user()->associate($request->user()->id);

        if($request->hasFile('image')) {
          $post->image =  $request->image->store(Post::IMAGE_PATH, 'public');
        }

        $post->save();

        return redirect()->route('post.all')->with(['status' => 'success', 'message' => 'Post successfully created.']);
    }

    public function edit($id, Request  $request)
    {
        $user = $request->user();
        $post = $user->posts()->findOrFail($id);
        $categories = Category::pluck('name', 'id');
        $posts = $user->posts()->paginate();

        return view('post.all', ['categories' => $categories, 'posts' => $posts, 'post' => $post]);
    }

    public function update($id, UpdatePost $request)
    {
        $user = $request->user();

        $post = $user->posts()->findOrFail($id);

        $post->name = $request->name;
        $post->category()->associate($request->category);

        if($request->hasFile('image')) {
            $post->image =  $request->image->store(Post::IMAGE_PATH, 'public');
        }

        $post->save();

        return redirect()->route('post.all')->with(['status' => 'success', 'message' => 'Post successfully updated.']);
    }

    public function show($id, Request  $request)
    {
        $user = $request->user();
        $post = $user->posts()->with('comments')->findOrFail($id);

        return view('post.show', ['post' => $post]);
    }
}

app/Http/Controllers/User/LoginController.php
<?php

namespace App\Http\Controllers\User;

use App\Http\Controllers\Controller;
use App\Http\Requests\LoginValidate;
use App\User;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;

class LoginController extends Controller
{
    public function __invoke()
    {
        return view('user.login');
    }

    public function submitForm(LoginValidate $request)
    {
        $userdata = array(
            'username' => $request->username,
            'password' => $request->password
        );

        // attempt to do the login
        if (Auth::attempt($userdata)) {

            $user = User::where('username', $request->username)->first();

            Auth::loginUsingId($user->id);

            return redirect()->route('post.all');
        }

        return redirect()->back()->with(['status' => 'danger', 'message' => 'Credential mismatch.']);
    }
    protected function guard()
    {
        return Auth::guard();
    }
}

app/Http/Controllers/User/RegisterController.php
<?php

namespace App\Http\Controllers\User;

use App\Http\Controllers\Controller;
use App\Http\Requests\ValidateUser;
use App\User;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Hash;

class RegisterController extends Controller
{

    public function __invoke()
    {
        return view('user.register');
    }

    public function submitForm(ValidateUser $request)
    {
        User::Create([
            'name' => $request->name,
            'username' => $request->username,
            'password' => Hash::make($request->password)
        ]);

        return redirect()->back()->with(['status' => 'success', 'message' => 'You have successfully registered with us.']);
    }
}

resources/views/layout/main.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="csrf-token" content="{{ csrf_token() }}">
    <title>Laravel</title>

    <!-- Fonts -->
    <link href="https://fonts.googleapis.com/css2?family=Nunito:wght@200;600&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.5.1.js"></script>
    <!-- Styles -->
    <style>
        html, body {
            background-color: #fff;
            color: #636b6f;
            font-family: 'Nunito', sans-serif;
            font-weight: 200;
            height: 100vh;
            margin: 0;
        }

        .full-height {
            height: 100vh;
        }

        .flex-center {
            align-items: center;
            display: flex;
            justify-content: center;
        }

        .position-ref {
            position: relative;
        }

        .top-right {
            position: absolute;
            right: 10px;
            top: 18px;
        }

        .content {
            text-align: center;
        }

        .title {
            font-size: 84px;
        }

        .links > a {
            color: #636b6f;
            padding: 0 25px;
            font-size: 13px;
            font-weight: 600;
            letter-spacing: .1rem;
            text-decoration: none;
            text-transform: uppercase;
        }

        .m-b-md {
            margin-bottom: 30px;
        }
    </style>
</head>
<body>

<div class="row justify-content-md-center">
    <div class="col-md-6 text-center mt-5 mb-5">
        @if(!auth()->user())
            <a class="btn btn-primary" href="{{ route('user.login') }}">Login</a>
            <a class="btn btn-dark" href="{{ route('user.register') }}">Register</a>
        @else
            <a class="btn btn-primary" href="{{ route('post.all') }}">All Post</a>
        @endif
    </div>
</div>

<div class="container">
    @yield('content')
</div>

</body>
</html>

resources/views/post/all.blade.php
@extends('layout.main')
@section('content')
    <div class="row {{ !$posts->count() ? 'justify-content-md-center' : '' }}">
        <div class="col-md-6 col">
            <h4>{{ $post->id ? 'Update' : 'Create' }} Post</h4>
            @if($post->id)
                {!! Form::model($post, ['route' => ['post.update', $post->id], 'files' => true]) !!}
                {!! method_field('PUT') !!}
            @else
            {!! Form::open(['route' => 'post.submit', 'files' => true]) !!}
            @endif
            @if(session()->get('status'))
                <div class="alert alert-success">{{ session()->get('message') }}</div>
            @endif
            <div class="form-group">
                <label for="formGroupExampleInput2">Post Name</label>
                <input type="text" class="form-control" id="formGroupExampleInput2" placeholder="Post Name" name="name" value="{{ old('name', $post->name) }}">
                <span class="alert-danger">
                         {!! $errors->first('name', ':message') !!}
                    </span>
            </div>

            <div class="form-group">
                <label for="formGroupExampleInput2">Category</label>
                {!! Form::select('category', $categories, old('category', $post->category_id), ['class' => 'form-control input']) !!}
                <span class="alert-danger">
                         {!! $errors->first('category', ':message') !!}
                    </span>
            </div>

            <div class="form-group">
                <label for="formGroupExampleInput2">Image</label>
                <input type="file" class="form-control" id="formGroupExampleInput2" name="image">
                <span class="alert-danger">
                         {!! $errors->first('image', ':message') !!}
                    </span>
            </div>

            <input type="submit" name="submit" value="Submit" class="btn btn-primary">

            @if($post->id)
                <a href="{{ route('post.all') }}" class="btn btn-dark">Create New Post</a>
            @endif
            </form>
        </div>

        @if($posts->count())
        <div class="col-md-6">
            <h4>All Post ({{ $posts->total() }})</h4>
            <table class="table table-striped">
                <thead>
                <tr>
                    <th scope="col">Name</th>
                    <th scope="col">Category</th>
                    <th scope="col">Image</th>
                    <th scope="col">Action</th>
                </tr>
                </thead>
                <tbody>
                @foreach($posts as $post)
                    <tr>
                        <td>{{ $post->name }}</td>
                        <td>{{ $post->category->name }}</td>
                        <td><img src="{{ $post->getImage() }}" style="height: 50px;"></td>
                        <td>
                            <a href="{{ route('post.edit', $post->id) }}" class="btn btn-sm btn-primary">Edit</a>
                            <a href="{{ route('post.show', $post->id) }}" class="btn btn-sm btn-dark">View</a>
                        </td>
                    </tr>
                @endforeach
                </tbody>
            </table>
            {!! $posts->links() !!}
        </div>
         @endif

    </div>

@endsection

resources/views/post/comment.blade.php
<div class="row">
    <div class="col-md-12">
        <strong>Username: {{ $comment->user->name }}</strong>
        <p>{{ $comment->comment }}</p>
        <hr>
    </div>
</div>

resources/views/post/show.blade.php
@extends('layout.main')
@section('content')
    <div class="row justify-content-md-center">
        <div class="col-md-7 col">
            <h4>Post: {{ $post->name }}</h4>
            <h6>Category: {{ $post->category->name }}</h6>
            <img class="img img-responsive" src="{{ $post->getImage() }}" />

            <hr>
            <h5>Comments (<span id="totalComment">{{ $post->comments()->count() }}</span>)</h5>
            {!! Form::open(['class' => 'form-inline', 'id' => 'ajax-form']) !!}
            <div class="row">
                <div class="form-group">
                    <label for="inputPassword2" class="sr-only">Comment</label>
                    <input type="text" class="form-control" id="comment" placeholder="Comment">
                </div>
                <button type="submit" class="btn btn-primary mb-2">Submit</button>
            </div>
            {!! Form::close() !!}

            <hr>

            @if($post->comments()->count())
                <div id="comments">
                    @foreach($post->comments as $comment)
                        @include('post.comment', ['comment' => $comment])
                    @endforeach
                </div>
            @endif

        </div>
    </div>

    <script type="text/javascript">

        jQuery("#ajax-form").on('submit', function (e){
           e.preventDefault();

            let $this = jQuery(this);
            let postId = '{{ $post->id }}';
            let comment = $this.find('#comment').val();


            jQuery.ajax({
                'method' : 'post',
                'url' : '/comment/submit/' + postId,
                dataType: 'json',
                data: { 'comment': comment },
                headers: {
                    'X-CSRF-Token': $('meta[name="csrf-token"]').attr('content')
                },
                success: function (response) {
                    jQuery("#comments").append(response.comment);
                    jQuery("#totalComment").text(response.total);
                },
                error(err) {
                    console.log(err);
                }
            })

        });


    </script>

@endsection

resources/views/user/login.blade.php
@extends('layout.main')
@section('content')
    <div class="row justify-content-md-center">
        <div class="col-md-6 col">
            <h4>Login</h4>
            {!! Form::open(['route' => 'user.login.submit']) !!}
            @if(session()->get('status'))
                <div class="alert alert-success">{{ session()->get('message') }}</div>
            @endif
            <div class="form-group">
                <label for="formGroupExampleInput2">Username</label>
                <input type="text" class="form-control" id="formGroupExampleInput2" placeholder="Username" name="username" value="{{ old('username') }}">
                <span class="alert-danger">
                         {!! $errors->first('username', ':message') !!}
                    </span>
            </div>
            <div class="form-group">
                <label for="formGroupExampleInput2">Password</label>
                <input type="password" class="form-control" id="formGroupExampleInput2" placeholder="Password" name="password" value="">
                <span class="alert-danger">
                         {!! $errors->first('name', ':password') !!}
                    </span>
            </div>
            <input type="submit" name="submit" value="Submit" class="btn btn-primary">
            </form>
        </div>
    </div>

@endsection

resources/views/user/register.blade.php
@extends('layout.main')
@section('content')
    <div class="row justify-content-md-center">
        <div class="col-md-6 col">
            <h4>Register</h4>
            {!! Form::open(['route' => 'user.register.submit']) !!}
                @if(session()->get('status'))
                    <div class="alert alert-success">{{ session()->get('message') }}</div>
                @endif
                <div class="form-group">
                    <label for="formGroupExampleInput">Name</label>
                    <input type="text" class="form-control" id="formGroupExampleInput" placeholder="Name" name="name" value="{{ old('name') }}">
                    <span class="alert-danger">
                         {!! $errors->first('name', ':message') !!}
                    </span>
                </div>
                <div class="form-group">
                    <label for="formGroupExampleInput2">Username</label>
                    <input type="text" class="form-control" id="formGroupExampleInput2" placeholder="Username" name="username" value="{{ old('username') }}">
                    <span class="alert-danger">
                         {!! $errors->first('username', ':message') !!}
                    </span>
                </div>
                <div class="form-group">
                    <label for="formGroupExampleInput2">Password</label>
                    <input type="password" class="form-control" id="formGroupExampleInput2" placeholder="Password" name="password" value="">
                    <span class="alert-danger">
                         {!! $errors->first('name', ':password') !!}
                    </span>
                </div>
                <input type="submit" name="submit" value="Submit" class="btn btn-primary">
            </form>
        </div>
    </div>

@endsection